yaml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -14,20 +14,22 @@ jobs:
       NEXT_PUBLIC_JWT_SECRET: dd5f3089-40c3-403d-af14-d0c228b05cb4
       NEXT_PUBLIC_JWT_REFRESH_TOKEN_SECRET: 7c4c1c50-3230-45bf-9eae-c9b2e401c767
       NEXT_PUBLIC_API: https://crownoffice-backend-production.up.railway.app/api
-      NEXT_PUBLIC_AUTH: https://evisa-travokey-authorization-production.up.railway.app/api
+      NEXT_PUBLIC_AUTH: http://89.116.21.11/authapi
 
     steps:
     - name: Checkout Repository
       uses: actions/checkout@v3
-
-    - name: Set Node.js Version
-      uses: actions/setup-node@v3
+      
+    - name: Cache Node Modules
+      uses: actions/cache@v2
       with:
-        node-version: 20.x
-        cache: 'npm'
-
+        path: node_modules
+        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+        restore-keys: |
+          ${{ runner.os }}-node-
+  
     - name: Install Dependencies
-      run: npm ci --force
+      run: npm ci
 
     - name: Build Application
       run: npm run build
@@ -35,11 +37,23 @@ jobs:
     - name: Optimize Memory Usage
       run: export NODE_OPTIONS="--max_old_space_size=4096"
 
-    - name: Stop Existing Process
-      run: pm2 stop "travokey-frontend" || true # '|| true' ensures that the workflow doesn't fail if pm2 stop fails
-
+    - name: Stop Existing PM2 Process if It Exists
+      run: |
+          if pm2 list | grep -q "travokey-auth"; then
+            pm2 delete "travokey-frontend"
+          else
+            echo "PM2 process 'travokey-frontend' not found, skipping stop command."
+          fi
     - name: Start Application
-      run: pm2 start travokey-frontend
+      run: pm2 start npm --name "travokey-frontend" -- run start
+  
+    # - name: Stop Existing Process
+    #   run: pm2 stop "travokey-frontend" || true # '|| true' ensures that the workflow doesn't fail if pm2 stop fails
+
+    # - name: Start Application
+    #   run: pm2 start travokey-frontend
 
     - name: Deployment Status
       run: echo "Deployment successfully!"
+
+      # pm2 start npm --name "travokey-frontend" -- run start
